# Render Blueprint for Owu Palace HRMS
# Using Neon DB for PostgreSQL database

services:
  # Backend Web Service
  - type: web
    name: owu-palace-backend
    env: node
    plan: free
    buildCommand: npm install --include=dev && npx prisma generate && npm run build
    startCommand: npm run start:prod
    rootDir: backend
    healthCheckPath: /api/health
    envVars:
      - key: NODE_ENV
        value: production
      - key: JWT_SECRET
        value: owu-palace-hrms-super-secret-jwt-key-2025-production
      - key: FRONTEND_URL
        value: https://owuhrms.netlify.app
      - key: DATABASE_URL
        value: postgresql://neondb_owner:npg_Qi8vM6ZFwHfa@ep-ancient-fog-a2qsngbk-pooler.eu-central-1.aws.neon.tech/neondb?sslmode=require
      - key: FILE_ENCRYPTION_KEY
        value: your-super-secret-encryption-key-change-in-production
      - key: MAX_FILE_SIZE
        value: 10485760
      - key: UPLOAD_PATH
        value: ./uploads
      - key: BCRYPT_ROUNDS
        value: 12

# No database section needed - using external Neon DB